apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spaghet
  namespace: tbd
  labels:
    team: tbd
spec:
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    requests:
      cpu: 50m
  replicas:
    min: 1
    scalingStrategy:
      kafka:
        topic: tbd.rapid.v1
        consumerGroup: tbd-spaghet-v1
        threshold: 200
  prometheus:
    enabled: true
    path: /metrics
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: spurtedu
        - application: speed-api
        - application: spedisjon
  azure:
    application:
      enabled: true
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spaghet-v1
    - name: KAFKA_RESET_POLICY
      value: earliest
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
