apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spaghet-db-policy-dev
  namespace: tbd
spec:
  egress:
    - to:
        - ipBlock:
            cidr: 35.228.166.116/32
  podSelector:
    matchLabels:
      db: spaghet
  policyTypes:
    - Egress