apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spaghet
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 64Mi
  replicas:
    min: 1
    max: 2
    scalingStrategy:
      kafka:
        topic: tbd.rapid.v1
        consumerGroup: tbd-spaghet-v1
        threshold: 200
  kafka:
    pool: nav-dev
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: spurtedu
        - application: speed-api
        - application: spedisjon
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        diskAutoresize: true
        name: spaghet2
        tier: db-f1-micro
        databases:
          - name: spaghet
            envVarPrefix: DATABASE
            users:
              - name: spaghetti
              - name: bigquery_datastream
        flags:
          - name: cloudsql.logical_decoding
            value: 'on'
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spaghet-v1
    - name: KAFKA_RESET_POLICY
      value: earliest
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
