apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spaghet
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 0
    max: 0
    cpuThresholdPercentage: 90
  ingresses:
    - https://spaghet.prod-fss.nais.io
  kafka:
    pool: nav-prod
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvspaghet
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spaghet-v1
    - name: KAFKA_RESET_POLICY
      value: earliest
    - name: DATABASE_HOST
      value: a01dbvl013.adeo.no
    - name: DATABASE_PORT
      value: "5432"
    - name: DATABASE_NAME
      value: spaghet
    - name: VAULT_MOUNTPATH
      value: postgresql/prod-fss/
    - name: RAPPORTERING_CHANNEL
      value: C014D9S8DD5
