apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spaghet
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 12
    scalingStrategy:
      kafka:
        topic: tbd.rapid.v1
        consumerGroup: tbd-spaghet-v1
        threshold: 200
  kafka:
    pool: nav-prod
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: spurtedu
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        diskAutoresize: true
        pointInTimeRecovery: true
        diskSize: 120
        diskType: SSD
        name: spaghet2
        tier: db-custom-4-16384
        databases:
          - name: spaghet
            envVarPrefix: DATABASE
            users:
              - name: spaghetti
              - name: bigquery_datastream
              - name: bigquery_connection_user
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spaghet-v1
    - name: KAFKA_RESET_POLICY
      value: earliest
