ALTER TABLE godkjenningsbehov ADD COLUMN inntektskilde VARCHAR(32) DEFAULT 'EN_ARBEIDSGIVER' NOT NULL;
ALTER TABLE godkjenningsbehov ALTER COLUMN inntektskilde DROP DEFAULT;

ALTER TABLE godkjenning ADD COLUMN inntektskilde VARCHAR(32) DEFAULT 'EN_ARBEIDSGIVER' NOT NULL;
ALTER TABLE godkjenning ALTER COLUMN inntektskilde DROP DEFAULT;